# Generated by Django 5.2.8 on 2025-11-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bankaccount_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('secure', 'Secure'), ('insecure', 'Insecure')], default='secure', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]

# James Scott (sba24070)
